title: Hello,It's me Apsal.
author: Apsal
email: your-apsalshbk550@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
   I'm an Engineering student, from the land of spices, Idukki. i'm doing Engineering degree in Mar Athanasius College of Engineering, Kothamangalam. I'm really crazy about football and a die-hard fan of Manchester United
# social links
twitter_username: https://twitter.com/_apzl
github_username: https://github.com/apzl

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
